package com.jakeapp.core.dao;
import com.jakeapp.core.domain.Account;
import com.jakeapp.core.domain.exceptions.InvalidCredentialsException;
import com.jakeapp.core.dao.exceptions.NoSuchServiceCredentialsException;
import java.util.UUID;
import java.util.List;

import com.jakeapp.core.util.InjectableTask;
import com.jakeapp.core.util.SpringThreadBroker;

public class ThreadedAccountDao implements IAccountDao {

	private IAccountDao dao;

	public ThreadedAccountDao(IAccountDao dao) {
		this.dao = dao;
	}

	// This file was automatically generated by generateDao.sh. Do not modify. 

	/**
	 * {@inheritDoc}
	 */	
	@Override
	public Account create(final Account credentials) 			throws InvalidCredentialsException {
		
		try {
			return SpringThreadBroker.getInstance().doTask(new InjectableTask<Account>() {

				@Override
				public Account calculate() throws Exception {
					return ThreadedAccountDao.this.dao.create(credentials);
				}
			});
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	
	}

	/**
	 * {@inheritDoc}
	 */	
	@Override
	public Account read(final UUID uuid) throws NoSuchServiceCredentialsException {
		
		try {
			return SpringThreadBroker.getInstance().doTask(new InjectableTask<Account>() {

				@Override
				public Account calculate() throws Exception {
					return ThreadedAccountDao.this.dao.read(uuid);
				}
			});
		} catch (NoSuchServiceCredentialsException  e) {
			throw e;
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	
	}

	/**
	 * {@inheritDoc}
	 */	
	@Override
	public List<Account> getAll() {
		
		try {
			return SpringThreadBroker.getInstance().doTask(new InjectableTask<List<Account>>() {

				@Override
				public List<Account> calculate() throws Exception {
					return ThreadedAccountDao.this.dao.getAll();
				}
			});
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	
	}

	/**
	 * {@inheritDoc}
	 */	
	@Override
	public Account update(final Account credentials) 			throws NoSuchServiceCredentialsException {
		
		try {
			return SpringThreadBroker.getInstance().doTask(new InjectableTask<Account>() {

				@Override
				public Account calculate() throws Exception {
					return ThreadedAccountDao.this.dao.update(credentials);
				}
			});
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	
	}

	/**
	 * {@inheritDoc}
	 */	
	@Override
	public void delete(final Account credentials) 			throws NoSuchServiceCredentialsException {
		
		try {
			SpringThreadBroker.getInstance().doTask(new InjectableTask<Void>() {

				@Override
				public Void calculate() throws Exception {
					ThreadedAccountDao.this.dao.delete(credentials);
					return null;
				}
			});
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	
	}


}
