/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginRegisterPanel.java
 *
 * Created on Nov 25, 2008, 5:01:39 PM
 */

package com.jakeapp.gui.swing.panels;

import com.jakeapp.gui.swing.JakeMainView;
import com.jakeapp.gui.swing.callbacks.ConnectionStatus;
import com.jakeapp.gui.swing.callbacks.RegistrationStatus;
import com.jakeapp.gui.swing.helpers.Platform;
import net.miginfocom.swing.MigLayout;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;

import javax.swing.*;
import java.awt.*;


/**
 * @author studpete
 */
public class LoginPanel extends javax.swing.JPanel implements RegistrationStatus, ConnectionStatus {
    private ResourceMap resourceMap;

    /**
     * Creates new form LoginRegisterPanel
     */
    public LoginPanel() {
        initComponents();
        setResourceMap(org.jdesktop.application.Application.getInstance(com.jakeapp.gui.swing.JakeMainApp.class).getContext().getResourceMap(LoginPanel.class));


        messageLabel.setText("<html><h1>Welcome to Jake</h1>To start sharing, you need to Sign In with an XMPP/Jabber-ID.<br>If you do not have such an ID, Jake will create one for you.</html>");

        loginRadioButton.setOpaque(false);
        registerRadioButton.setOpaque(false);
        rememberPasswordCheckBox.setOpaque(false);

        // set the background painter
        loginHeaderPanel.setBackgroundPainter(Platform.getStyler().getContentPanelBackgroundPainter());

        // make initial update
        selectionChanged();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginHeaderPanel = new org.jdesktop.swingx.JXPanel();
        mainLoginPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        messagePanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        loginControlPanel = new org.jdesktop.swingx.JXPanel();
        signInRegisterButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameComboBox = new javax.swing.JComboBox();
        rememberPasswordCheckBox = new javax.swing.JCheckBox();
        registerRadioButton = new javax.swing.JRadioButton();
        loginRadioButton = new javax.swing.JRadioButton();
        advancedServerOptionsHolderPanel = new javax.swing.JPanel();
        advancedServerOptionsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jakeapp.gui.swing.JakeMainApp.class).getContext().getResourceMap(LoginPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        loginHeaderPanel.setBackground(resourceMap.getColor("loginHeaderPanel.background")); // NOI18N
        loginHeaderPanel.setName("loginHeaderPanel"); // NOI18N
        loginHeaderPanel.setLayout(new javax.swing.BoxLayout(loginHeaderPanel, javax.swing.BoxLayout.X_AXIS));

        mainLoginPanel.setName("mainLoginPanel"); // NOI18N
        mainLoginPanel.setOpaque(false);

        javax.swing.GroupLayout mainLoginPanelLayout = new javax.swing.GroupLayout(mainLoginPanel);
        mainLoginPanel.setLayout(mainLoginPanelLayout);
        mainLoginPanelLayout.setHorizontalGroup(
                mainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        mainLoginPanelLayout.setVerticalGroup(
                mainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 509, Short.MAX_VALUE)
        );

        loginHeaderPanel.add(mainLoginPanel);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        messagePanel.setName("messagePanel"); // NOI18N
        messagePanel.setOpaque(false);

        messageLabel.setName("messageLabel"); // NOI18N

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addGap(67, 67, 67))
        );
        messagePanelLayout.setVerticalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
        );

        mainPanel.add(messagePanel);

        loginControlPanel.setMaximumSize(new java.awt.Dimension(491, 348));
        loginControlPanel.setMinimumSize(new java.awt.Dimension(491, 348));
        loginControlPanel.setName("loginControlPanel"); // NOI18N
        loginControlPanel.setOpaque(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.jakeapp.gui.swing.JakeMainApp.class).getContext().getActionMap(LoginPanel.class, this);
        signInRegisterButton.setAction(actionMap.get("signIn")); // NOI18N
        signInRegisterButton.setText(resourceMap.getString("signInRegisterButton.text")); // NOI18N
        signInRegisterButton.setName("signInRegisterButton"); // NOI18N

        passwordLabel.setForeground(resourceMap.getColor("passwordLabel.foreground")); // NOI18N
        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N

        usernameLabel.setForeground(resourceMap.getColor("usernameLabel.foreground")); // NOI18N
        usernameLabel.setText(resourceMap.getString("usernameLabel.text")); // NOI18N
        usernameLabel.setName("usernameLabel"); // NOI18N

        usernameComboBox.setEditable(true);
        usernameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"   ", "pstein", "csutter"}));
        usernameComboBox.setName("usernameComboBox"); // NOI18N

        rememberPasswordCheckBox.setSelected(true);
        rememberPasswordCheckBox.setText(resourceMap.getString("rememberPasswordCheckBox.text")); // NOI18N
        rememberPasswordCheckBox.setName("rememberPasswordCheckBox"); // NOI18N

        registerRadioButton.setAction(actionMap.get("selectionChanged")); // NOI18N
        buttonGroup1.add(registerRadioButton);
        registerRadioButton.setText(resourceMap.getString("registerRadioButton.text")); // NOI18N
        registerRadioButton.setName("registerRadioButton"); // NOI18N

        loginRadioButton.setAction(actionMap.get("selectionChanged")); // NOI18N
        buttonGroup1.add(loginRadioButton);
        loginRadioButton.setSelected(true);
        loginRadioButton.setText(resourceMap.getString("loginRadioButton.text")); // NOI18N
        loginRadioButton.setName("loginRadioButton"); // NOI18N

        advancedServerOptionsHolderPanel.setMinimumSize(new java.awt.Dimension(396, 63));
        advancedServerOptionsHolderPanel.setName("advancedServerOptionsHolderPanel"); // NOI18N
        advancedServerOptionsHolderPanel.setOpaque(false);
        advancedServerOptionsHolderPanel.setLayout(new java.awt.BorderLayout());

        advancedServerOptionsPanel.setMinimumSize(new java.awt.Dimension(358, 46));
        advancedServerOptionsPanel.setName("advancedServerOptionsPanel"); // NOI18N
        advancedServerOptionsPanel.setOpaque(false);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"jabber.fsinf.at", "jabber.org", "jabber.ccc.de", "macjabber.de", "swissjabber.ch", "binaryfreedom.info"}));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout advancedServerOptionsPanelLayout = new javax.swing.GroupLayout(advancedServerOptionsPanel);
        advancedServerOptionsPanel.setLayout(advancedServerOptionsPanelLayout);
        advancedServerOptionsPanelLayout.setHorizontalGroup(
                advancedServerOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(advancedServerOptionsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(17, 17, 17))
        );
        advancedServerOptionsPanelLayout.setVerticalGroup(
                advancedServerOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(advancedServerOptionsPanelLayout.createSequentialGroup()
                        .addGroup(advancedServerOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        advancedServerOptionsHolderPanel.add(advancedServerOptionsPanel, java.awt.BorderLayout.CENTER);

        passwordField.setText(resourceMap.getString("passwordField.text")); // NOI18N
        passwordField.setName("passwordField"); // NOI18N

        javax.swing.GroupLayout loginControlPanelLayout = new javax.swing.GroupLayout(loginControlPanel);
        loginControlPanel.setLayout(loginControlPanelLayout);
        loginControlPanelLayout.setHorizontalGroup(
                loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginControlPanelLayout.createSequentialGroup()
                        .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(loginControlPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(signInRegisterButton))
                                .addGroup(loginControlPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(loginControlPanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameComboBox, 0, 383, Short.MAX_VALUE)
                                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                        .addComponent(rememberPasswordCheckBox)
                                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)))
                                .addGroup(loginControlPanelLayout.createSequentialGroup()
                                .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(loginControlPanelLayout.createSequentialGroup()
                                                .addComponent(registerRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                                .addGap(149, 149, 149))
                                        .addGroup(loginControlPanelLayout.createSequentialGroup()
                                                .addComponent(loginRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                                .addGap(89, 89, 89))
                                        .addComponent(advancedServerOptionsHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)))))
                        .addGap(45, 45, 45))
        );
        loginControlPanelLayout.setVerticalGroup(
                loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registerRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(advancedServerOptionsHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLabel)
                        .addGap(1, 1, 1)
                        .addComponent(usernameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordLabel)
                        .addGap(2, 2, 2)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rememberPasswordCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signInRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))
        );

        mainPanel.add(loginControlPanel);

        loginHeaderPanel.add(mainPanel);

        add(loginHeaderPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void selectionChanged() {
        advancedServerOptionsPanel.setVisible(registerRadioButton.isSelected());

        // update the button
        udpdateSignInRegisterButton();

    }

    private void udpdateSignInRegisterButton() {
        if (isModeSignIn()) {
            signInRegisterButton.setText(getResourceMap().getString("loginSignIn"));
        } else {
            signInRegisterButton.setText(getResourceMap().getString("loginRegister"));
        }
    }

    private boolean isModeSignIn() {
        return loginRadioButton.isSelected();
    }

    @Action
    public void signIn() {


        if (isModeSignIn()) {
            JakeMainView.getMainView().getCore().signIn(usernameLabel.getText(), passwordLabel.getText());
        } else {
            JakeMainView.getMainView().getCore().register(usernameLabel.getText(), passwordLabel.getText());
        }


        loginControlPanel.setVisible(false);

        messageLabel.setText("<html><h1>Success!</h1>You are now signed in as <em>peter@fsinf.ac.at</em><br><b>Drag&Drop a Folder into the App to start sharing.</html>");


        // TODO: extract, fix, i18n, ...

        JPanel loginSuccessPanel = new JPanel();
        loginSuccessPanel.setOpaque(false);
        loginSuccessPanel.setLayout(new MigLayout("nogrid, fillx"));

        JLabel iconSuccess = new JLabel();
        iconSuccess.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(
                getClass().getResource("/icons/dropfolder.png"))));

        loginSuccessPanel.add(iconSuccess, "wrap, al center");

        JLabel messageSuccess = new JLabel("Drag and drop folders you wanna share here.");
        messageSuccess.setFont(Platform.getStyler().getH1Font());
        messageSuccess.setForeground(Color.DARK_GRAY);

        loginSuccessPanel.add(messageSuccess, "al center");

        mainPanel.remove(loginControlPanel);
        mainPanel.add(loginSuccessPanel);
        mainPanel.updateUI();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advancedServerOptionsHolderPanel;
    private javax.swing.JPanel advancedServerOptionsPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private org.jdesktop.swingx.JXPanel loginControlPanel;
    private org.jdesktop.swingx.JXPanel loginHeaderPanel;
    private javax.swing.JRadioButton loginRadioButton;
    private javax.swing.JPanel mainLoginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JRadioButton registerRadioButton;
    private javax.swing.JCheckBox rememberPasswordCheckBox;
    private javax.swing.JButton signInRegisterButton;
    private javax.swing.JComboBox usernameComboBox;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables


    public void setRegistrationStatus(RegisterStati status) {
    }

    public void setConnectionStatus(ConnectionStati status) {
    }

    public ResourceMap getResourceMap() {
        return resourceMap;
    }

    public void setResourceMap(ResourceMap resourceMap) {
        this.resourceMap = resourceMap;
    }
}
