/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginRegisterPanel.java
 *
 * Created on Nov 25, 2008, 5:01:39 PM
 */

package com.jakeapp.gui.swing.panels;

import java.awt.Color;

import org.jdesktop.application.Action;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.GlossPainter;
import org.jdesktop.swingx.painter.MattePainter;
import org.jdesktop.swingx.painter.PinstripePainter;

import com.jakeapp.gui.swing.helpers.Colors;

/**
 * @author studpete
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginRegisterPanel
     */
    public LoginPanel() {
        initComponents();

        messageLabel.setText("<html><h1>Welcome to Jake</h1>To start sharing, you need to Sign In with an XMPP/Jabber-ID.<br>If you do not have such an ID, Jake will create one for you.</html>");

        loginControlPanel.setBackground(Color.RED);

        loginRadioButton.setOpaque(false);
        registerRadioButton.setOpaque(false);
        rememberPasswordCheckBox.setOpaque(false);

        // set the background painter
        MattePainter mp = new MattePainter(Colors.LightBlue.alpha(0.5f));
        GlossPainter gp = new GlossPainter(Colors.White.alpha(0.3f),
                GlossPainter.GlossPosition.TOP);
        PinstripePainter pp = new PinstripePainter(Colors.Gray.alpha(0.1f),
                45d);
        loginHeaderPanel.setBackgroundPainter(new CompoundPainter(mp, pp, gp));


        // make initial update
        selectionChanged();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginHeaderPanel = new org.jdesktop.swingx.JXPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        messagePanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        loginControlPanel = new org.jdesktop.swingx.JXPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        rememberPasswordCheckBox = new javax.swing.JCheckBox();
        registerRadioButton = new javax.swing.JRadioButton();
        loginRadioButton = new javax.swing.JRadioButton();
        advancedServerOptionsHolderPanel = new javax.swing.JPanel();
        advancedServerOptionsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jakeapp.gui.swing.JakeMainApp.class).getContext().getResourceMap(LoginPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        loginHeaderPanel.setBackground(resourceMap.getColor("loginHeaderPanel.background")); // NOI18N
        loginHeaderPanel.setName("loginHeaderPanel"); // NOI18N
        loginHeaderPanel.setLayout(new javax.swing.BoxLayout(loginHeaderPanel, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 509, Short.MAX_VALUE)
        );

        loginHeaderPanel.add(jPanel3);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        messagePanel.setName("messagePanel"); // NOI18N
        messagePanel.setOpaque(false);

        messageLabel.setName("messageLabel"); // NOI18N

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addGap(67, 67, 67))
        );
        messagePanelLayout.setVerticalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(messagePanel);

        loginControlPanel.setMaximumSize(new java.awt.Dimension(491, 348));
        loginControlPanel.setMinimumSize(new java.awt.Dimension(491, 348));
        loginControlPanel.setName("loginControlPanel"); // NOI18N
        loginControlPanel.setOpaque(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.jakeapp.gui.swing.JakeMainApp.class).getContext().getActionMap(LoginPanel.class, this);
        jButton1.setAction(actionMap.get("signIn")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"pstein", "csutter"}));
        jComboBox2.setName("jComboBox2"); // NOI18N

        rememberPasswordCheckBox.setSelected(true);
        rememberPasswordCheckBox.setText(resourceMap.getString("rememberPasswordCheckBox.text")); // NOI18N
        rememberPasswordCheckBox.setName("rememberPasswordCheckBox"); // NOI18N

        registerRadioButton.setAction(actionMap.get("selectionChanged")); // NOI18N
        buttonGroup1.add(registerRadioButton);
        registerRadioButton.setText(resourceMap.getString("registerRadioButton.text")); // NOI18N
        registerRadioButton.setName("registerRadioButton"); // NOI18N

        loginRadioButton.setAction(actionMap.get("selectionChanged")); // NOI18N
        buttonGroup1.add(loginRadioButton);
        loginRadioButton.setSelected(true);
        loginRadioButton.setText(resourceMap.getString("loginRadioButton.text")); // NOI18N
        loginRadioButton.setName("loginRadioButton"); // NOI18N

        advancedServerOptionsHolderPanel.setMinimumSize(new java.awt.Dimension(396, 63));
        advancedServerOptionsHolderPanel.setName("advancedServerOptionsHolderPanel"); // NOI18N
        advancedServerOptionsHolderPanel.setOpaque(false);
        advancedServerOptionsHolderPanel.setLayout(new java.awt.BorderLayout());

        advancedServerOptionsPanel.setMinimumSize(new java.awt.Dimension(358, 46));
        advancedServerOptionsPanel.setName("advancedServerOptionsPanel"); // NOI18N
        advancedServerOptionsPanel.setOpaque(false);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"jabber.fsinf.at"}));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout advancedServerOptionsPanelLayout = new javax.swing.GroupLayout(advancedServerOptionsPanel);
        advancedServerOptionsPanel.setLayout(advancedServerOptionsPanelLayout);
        advancedServerOptionsPanelLayout.setHorizontalGroup(
                advancedServerOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(advancedServerOptionsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(17, 17, 17))
        );
        advancedServerOptionsPanelLayout.setVerticalGroup(
                advancedServerOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(advancedServerOptionsPanelLayout.createSequentialGroup()
                        .addGroup(advancedServerOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        advancedServerOptionsHolderPanel.add(advancedServerOptionsPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout loginControlPanelLayout = new javax.swing.GroupLayout(loginControlPanel);
        loginControlPanel.setLayout(loginControlPanelLayout);
        loginControlPanelLayout.setHorizontalGroup(
                loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginControlPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(loginControlPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBox2, 0, 383, Short.MAX_VALUE)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                                .addComponent(rememberPasswordCheckBox)))
                                        .addGroup(loginControlPanelLayout.createSequentialGroup()
                                        .addGroup(loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(loginControlPanelLayout.createSequentialGroup()
                                                        .addComponent(registerRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                                        .addGap(149, 149, 149))
                                                .addGroup(loginControlPanelLayout.createSequentialGroup()
                                                        .addComponent(loginRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                                        .addGap(89, 89, 89))
                                                .addComponent(advancedServerOptionsHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3)))
                                .addGap(45, 45, 45))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginControlPanelLayout.createSequentialGroup()
                        .addContainerGap(345, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(59, 59, 59))
        );
        loginControlPanelLayout.setVerticalGroup(
                loginControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registerRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(advancedServerOptionsHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rememberPasswordCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.add(loginControlPanel);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 491, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        loginHeaderPanel.add(jPanel2);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 509, Short.MAX_VALUE)
        );

        loginHeaderPanel.add(jPanel1);

        add(loginHeaderPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void selectionChanged() {
        //for(Component comp : advancedServerOptionsPanel.getComponents()) {
        advancedServerOptionsPanel.setVisible(registerRadioButton.isSelected());
        // }

    }

    @Action
    public void signIn() {
        loginControlPanel.setVisible(false);

        messageLabel.setText("<html><h1>Success!</h1>You are now signed in as <em>peter@fsinf.ac.at</em><br><b>Drag&Drop a Folder into the App to start sharing.</html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advancedServerOptionsHolderPanel;
    private javax.swing.JPanel advancedServerOptionsPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXPanel loginControlPanel;
    private org.jdesktop.swingx.JXPanel loginHeaderPanel;
    private javax.swing.JRadioButton loginRadioButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JRadioButton registerRadioButton;
    private javax.swing.JCheckBox rememberPasswordCheckBox;
    // End of variables declaration//GEN-END:variables

}
