/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotesPanel.java
 *
 * Created on Dec 3, 2008, 2:00:15 AM
 */

package com.jakeapp.gui.swing.panels;

import com.jakeapp.gui.swing.helpers.Colors;
import com.jakeapp.gui.swing.listener.TableMouseListener;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.GlossPainter;
import org.jdesktop.swingx.painter.MattePainter;

import javax.swing.*;
import java.awt.*;

/**
 * @author studpete
 */
public class NotesPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotesPanel
     */
    public NotesPanel() {
        initComponents();

        notesTable.setSortable(true);
        notesTable.setColumnControlVisible(true);
        notesTable.setHighlighters(HighlighterFactory.createSimpleStriping());

        final PopupMenu notesPopupMenu = new PopupMenu();
        this.add(notesPopupMenu);

        notesPopupMenu.add(new MenuItem("Open"));
        notesPopupMenu.add(new MenuItem("New..."));
        notesPopupMenu.add(new MenuItem("Delete"));


        notesTable.addMouseListener(new TableMouseListener(notesTable) {

            @Override
            public void showPopup(JComponent comp, int x, int y) {
                notesPopupMenu.show(comp, x, y);
            }

            @Override
            public void editAction() {

                // Get the frame
                JFrame frame = (JFrame) SwingUtilities.getRoot(notesTable);

                //AddEditNoteDialog.ShowAsDialog(new Object(), frame);
            }
        });


        JTextArea noteReader = new JTextArea();
        // noteReader.setBorder(new LineBorder(Color.BLACK, 1));
        noteReader.setLineWrap(true);
        noteReader.setOpaque(false);
        noteReader.setText("Enter your Note here.\nChanges will be saved automatically.");
        noteReader.setMargin(new Insets(8, 8, 8, 8));

        JScrollPane noteReaderScrollPane = new JScrollPane(noteReader);
        noteReaderScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        noteReaderScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        //noteReaderScrollPane.setBounds(70, 479, 278, 111);
        noteReaderScrollPane.setOpaque(false);
        noteReaderScrollPane.getViewport().setOpaque(false);
        ;

        noteReadPanel.add(noteReaderScrollPane);


        // set the background painter
        MattePainter mp = new MattePainter(Colors.Yellow.alpha(0.5f));
        GlossPainter gp = new GlossPainter(Colors.White.alpha(0.3f),
                GlossPainter.GlossPosition.TOP);
        //PinstripePainter pp = new PinstripePainter(Colors.White.alpha(0.1f),
        //                                          45d);
        noteReadPanel.setBackgroundPainter(new CompoundPainter(mp, gp));
    }

    private boolean isNoteSelected() {
        return notesTable.getSelectedRow() >= 0;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesTable = new org.jdesktop.swingx.JXTable();
        noteReadPanel = new org.jdesktop.swingx.JXPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        notesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {"Gui redesign nicht vergessen...", "8.12.2008 18:00", "Peter"},
                        {"Blabla", "9.12.2008", "Simon"},
                        {"xxx", "10.12", "a"},
                        {"bbb", "11.12", "b"}
                },
                new String[]{
                        "Note", "Date", "User"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        notesTable.setName("notesTable"); // NOI18N
        jScrollPane2.setViewportView(notesTable);

        jSplitPane1.setLeftComponent(jScrollPane2);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jakeapp.gui.swing.JakeMainApp.class).getContext().getResourceMap(NotesPanel.class);
        noteReadPanel.setBackground(resourceMap.getColor("noteReadPanel.background")); // NOI18N
        noteReadPanel.setName("noteReadPanel"); // NOI18N
        noteReadPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(noteReadPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private org.jdesktop.swingx.JXPanel noteReadPanel;
    private org.jdesktop.swingx.JXTable notesTable;
    // End of variables declaration//GEN-END:variables

}
