package com.jakeapp.violet.di;

public enum KnownProperty {
	JDBCDB, JDBCUSER, JDBCPASSWORD, PROJECT_FILENAMES_LOG, PROJECT_FILENAMES_PREFERENCES, DB_CREATELOGTABLE, DB_CREATELOGINDEXWHEN, DB_CREATELOGINDEXWHAT, DB_INSERTLOG, DB_GETLOGBYID, DB_GETRELPATHSPROCESSED, DB_GETRELPATHS, DB_SETPROCESSEDFORWHAT, DB_SETPROCESSEDBYID, DB_GETALL, DB_GETPROCESSED, DB_GETUNPROCESSED, DB_GETALLFORWHAT, DB_GETPROCESSEDFORWHAT, DB_GETUNPROCESSEDFORWHAT, ICS_RESOURCE_NAME, ICS_RESOURCE_PROJECT_PREFIX, GLOBAL_PROJECTS_FILENAME, GLOBAL_SETTINGS_DIR, ICS_USE_SOCKETS, USE_TRASH;

	String v;

	KnownProperty(String v) {
		this.v = v;
	}

	KnownProperty() {
		this.v = toString().toLowerCase().replace("_", ".");
	}
}
